import Head from 'next/head';

import Navbar from '@/components/Navbar';
import ThemeChanger from '@/components/ThemeChanger';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <main className='dark:bg-neutral-900 min-h-screen flex items-center justify-center flex-wrap'>
        <div className='p-8'>
          <h1 className='text-4xl text-neutral-800 dark:text-white font-semibold tracking-wide mb-4'>
            <a href='https://nextjs.org' className='text-sky-600 hover:text-sky-700 transition-all'>
              Next.js
            </a>{' '}
            +{' '}
            <a href='https://tailwindcss.com' className='text-cyan-600 hover:text-cyan-700 transition-all'>
              Tailwind CSS
            </a>
          </h1>
          <div className='flex justify-center gap-4'>
            <ThemeChanger />
          </div>
        </div>
      </main>
    </div>
  );
}
